blank_issues_enabled: false
contact_links:
  - name: â“ Help and Support Slack Channel
    url: https://ibm-research.slack.com/archives/C04AGHGSHQS
    about: Please ask and answer questions here. ğŸ¥
